# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170124_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='finish_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
