# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170124_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='air_conditioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='duration',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_seats',
            field=models.IntegerField(default=0),
        ),
    ]
