# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170124_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
