# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170124_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
