# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170124_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
