# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170125_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='room_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.IntegerField(),
        ),
    ]
