# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170128_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_of_booking',
        ),
    ]
