# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_books_date_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_of_booking',
            field=models.DateField(null=True),
        ),
    ]
