# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170129_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='finish_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
